################################### Default Configuration ############################
baseURL = "https://inspired.digital"
languageCode = "en-us"
title = "SEO Services & Niche Site Builders - Inspired.digital"
theme = "agen-hugo"

#################################### Plugins ##########################################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"
  [[params.plugins.css]]
  URL = "plugins/card-slider/css/style.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/shuffle/shuffle.min.js"
  [[params.plugins.js]]
  URL = "plugins/counto/apear.js"
  [[params.plugins.js]]
  URL = "plugins/counto/counTo.js"
  [[params.plugins.js]]
  URL = "plugins/card-slider/js/card-slider-min.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/gmap.js"


###################################### Navigation ######################################
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2

  [[menu.main]]
  name = "SEO Services"
  URL = "service"
  weight = 3
  hasChildren = true

    [[menu.main]]
    parent = "SEO Services"
    name = "SEO Consulting"
    URL = "service/seo-consulting"

    [[menu.main]]
    parent = "SEO Services"
    name = "Technical SEO"
    URL = "service/technical-seo"

    [[menu.main]]
    parent = "SEO Services"
    name = "Link Building"
    URL = "service/link-building"

    [[menu.main]]
    parent = "SEO Services"
    name = "E-commerce SEO"
    URL = "service/ecommerce-seo"

    [[menu.main]]
    parent = "SEO Services"
    name = "Local SEO"
    URL = "service/local-seo"

    [[menu.main]]
    parent = "SEO Services"
    name = "Content"
    URL = "service/content"

    [[menu.main]]
    parent = "SEO Services"
    name = "Reporting and Dashboards"
    URL = "service/reporting-and-dashboards"

    [[menu.main]]
    parent = "SEO Services"
    name = "Keyword Research"
    URL = "service/keyword-research"

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 4

  [[menu.main]]
  name = "Learn"
  weight = 5
  hasChildren = true

    [[menu.main]]
    parent = "Learn"
    name = "Training"
    URL = "training"

    [[menu.main]]
    parent = "Learn"
    name = "Courses"
    URL = "courses"

    #[[menu.main]]
    #parent = "pages"
    #name = "Blog"
    #URL = "blog"

    #[[menu.main]]
    #parent = "pages"
    #name = "Career"
    #URL = "career"

    #[[menu.main]]
    #parent = "pages"
    #name = "FAQs"
    #URL = "faqs"

    #[[menu.main]]
    #parent = "pages"
    #name = "Pricing"
    #URL = "pricing"

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 6

  ############################# Footer menu ################################
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 2

  [[menu.footer]]
  name = "SEO Services"
  URL = "service"
  weight = 3

  #[[menu.footer]]
  #name = "Portfolio"
  #URL = "portfolio"
  #weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 4

########################### Default parameters ##########################
[params]
logo = "images/inspired-digital-white-logo.png"
home = "Home"
# Meta data AIzaSyBfiNRI21OWZnNKd1aRzjN3-5aUxEyZW5o

description = "This is meta description"
author = "Inspired Digital"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBfiNRI21OWZnNKd1aRzjN3-5aUxEyZW5o&libraries=places"
mapLatitude = "51.5127998"
mapLongitude = "-0.3075489"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "Your ID"

  # Preloader
  [params.preloader]
  enable = false

  ############################# Footer Start ###########################

  # footer about
  [params.footer.about]
  about = "Inspired Digital is more than just SEO, we are a dedicated team of online marketing experts who also specialise in niche site building.  We offer tailored SEO services to supercharge your business in Google"

  # contact form
  [params.form]
  formAction = "https://formspree.io/f/maykydqy"

  # copyright
  [params.copyright]
  copyright = "Copyright &copy; 2022 [Inspired.digital](https://inspired.digital)"

  ######################### Social site ##############################
  [[params.social]]
  icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
  link = "#"

  [[params.social]]
  icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
  link = "#"

  [[params.social]]
  icon = "ti-github" # themify icon pack https://themify.me/themify-icons
  link = "#"

  [[params.social]]
  icon = "ti-instagram" # themify icon pack https://themify.me/themify-icons
  link = "#"
