baseURL = "https://inspired.digital"
languageCode = "en-us"
title = "Inspired Digital"
theme = "dtox"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/Venobox/venobox.css"
  [[params.plugins.css]]
  URL = "plugins/aos/aos.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/aos/aos.js"
  [[params.plugins.js]]
  URL = "plugins/Venobox/venobox.min.js"


# Menu
[menu]
  [[menu.main]]
  name = "Features"
  URL = "#feature"
  weight = 2

  [[menu.main]]
  name = "About"
  URL = "about/"
  weight = 3
  
  [[menu.main]]
  name = "Services"
  URL = "service/"
  weight = 4

  [[menu.main]]
  name = "Team"
  URL = "#team"
  weight = 5
  
  [[menu.main]]
  name = "Pricing"
  URL = "#pricing"
  weight = 6

  [[menu.main]]
  name = "Contact"
  URL = "contact/"
  weight = 7



[params]
logo = "images/inspired-logo3.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Inspired Digital"
# Google Analitycs
googleAnalitycsID = "Your ID"

  # Preloader
  [params.preloader]
  enable = false

  # Navigation button
  [params.navBtn]
  enable = true
  btnText = "Let's Go! 🚀"
  URL = "#"

  # Banner
  [params.banner]
  title = "Want to do SEO? <br> Get Inspired."
  content = "We provide an affordable SEO platform that allows you to take control of your organic rankings <br> and we're also there to help if you need us."
  bgImage = "images/hero-area/banner-bg.svg"
  image = "images/hero-area/banner-img.png"
  btnText = "explore us"
  URL = "#"
    [params.banner.bgShape]
    enable = true


  # footer
  [params.footer]
  bgImage = "images/backgrounds/footer-bg.svg"
  
    [[params.footer.socialIcon]]
    icon = "ti-facebook"
    color = "facebook"
    URL = "#"

    [[params.footer.socialIcon]]
    icon = "ti-twitter-alt"
    color = "twitter"
    URL = "#"

    [[params.footer.socialIcon]]
    icon = "ti-linkedin"
    color = "linkedin"
    URL = "#"

    [[params.footer.socialIcon]]
    icon = "ti-github"
    color = "black"
    URL = "#"